# Your fourth SPARQL query:
# People who are not painters and are student of painters
SELECT DISTINCT ?student
WHERE 
{
  ?painter wdt:P31 wd:Q5 ; # find humans
        wdt:P106 wd:Q1028181 . # who are painters
  ?student  wdt:P31 wd:Q5 ; # find humans
        wdt:P1066 | ^wdt:P802  ?painter # inverse student or student of ?painter
    MINUS { ?student wdt:P106 wd:Q1028181 . }
}


